[book]
language = "en"
multilingual = false
src = "src"
title = "Cluster API Addon Provider Fleet"
description = "Addon for native Fleet GitOps integration with CAPI"

[preprocessor.toc]
command = "mdbook-toc"
marker = "[[_TOC_]]"

[preprocessor.fs-summary]
# (default: true)
clean-paths = false

# other preprocessors will naturally need to 
# run after the summary has been generated 
[preprocessor.links]
after = ["fs-summary"] 

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/rancher-sandbox/cluster-api-addon-provider-fleet"
git-repository-icon = "fa-github"
site-url = "/caapf/"

