name: Run CI checks

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, labeled, unlabeled]
  merge_group:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install just
        uses: extractions/setup-just@v2
      - uses: actions/checkout@v4
      - name: Build
        run: just compile
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install just
        uses: extractions/setup-just@v2
      - uses: actions/checkout@v4
      - name: Test
        run: just test-unit
  test-e2e-cluster-class:
    runs-on: ubuntu-latest
    steps:
      - name: Install just
        uses: extractions/setup-just@v2
      - name: Install kind
        uses: helm/kind-action@v1
        with:
          install_only: true
          version: v0.26.0
      - uses: actions/checkout@v4
      - name: Test
        run: just test-cluster-class-import
      - name: Collect artifacts
        if: always()
        run: just collect-test-cluster-class-import
      - name: Store run artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: artifacts-cluster-class-import
          path: _out/gather
  test-e2e-import:
    runs-on: ubuntu-latest
    steps:
      - name: Install just
        uses: extractions/setup-just@v2
      - name: Install kind
        uses: helm/kind-action@v1
        with:
          install_only: true
          version: v0.26.0
      - uses: actions/checkout@v4
      - name: Test
        run: just test-import
      - name: Collect artifacts
        if: always()
        run: just collect-test-import
      - name: Store run artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: artifacts-import
          path: _out/gather
