name: Run CI checks

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, labeled, unlabeled]
  merge_group:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install just
        run: cargo install just
      - uses: actions/checkout@v4
      - name: Build
        run: just compile

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install just
        run: cargo install just
      - uses: actions/checkout@v4
      - name: Test
        run: just test-unit

  test-e2e:
    name: test-e2e ${{ matrix.display_name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - kube_version: "1.30.4"
            display_name: "stable"
          - kube_version: "1.32.0"
            display_name: "latest"
    env:
      KUBE_VERSION: ${{ matrix.kube_version }}
    steps:
      - name: Install just
        run: cargo install just
      - name: Install kind
        uses: helm/kind-action@v1
        with:
          install_only: true
          version: v0.26.0
      - uses: actions/checkout@v4
      - name: Test (Cluster Class) - ${{ matrix.display_name }}
        run: just test-cluster-class-import
      - name: Collect artifacts
        if: always()
        run: just collect-test-cluster-class-import
      - name: Store run artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: artifacts-cluster-class-import-${{ matrix.display_name }}
          path: _out/gather

  test-e2e-import:
    name: test-e2e-import ${{ matrix.display_name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - kube_version: "1.30.4"
            display_name: "stable"
          - kube_version: "1.32.0"
            display_name: "latest"
    env:
      KUBE_VERSION: ${{ matrix.kube_version }}
    steps:
      - name: Install just
        run: cargo install just
      - name: Install kind
        uses: helm/kind-action@v1
        with:
          install_only: true
          version: v0.26.0
      - uses: actions/checkout@v4
      - name: Test (Import) - ${{ matrix.display_name }}
        run: just test-import
      - name: Collect artifacts
        if: always()
        run: just collect-test-import
      - name: Store run artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: artifacts-import-${{ matrix.display_name }}
          path: _out/gather

  test-e2e-import-rke2:
    name: test-e2e-import-rke2 ${{ matrix.display_name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - kube_version: "1.30.4"
            display_name: "stable"
          - kube_version: "1.32.0"
            display_name: "latest"
    env:
      KUBE_VERSION: ${{ matrix.kube_version }}
    steps:
      - name: Install just
        run: cargo install just
      - name: Install kind
        uses: helm/kind-action@v1
        with:
          install_only: true
          version: v0.26.0
      - uses: actions/checkout@v4
      - name: Test (Import RKE2) - ${{ matrix.display_name }}
        run: just test-import-rke2
      - name: Collect artifacts
        if: always()
        run: just collect-test-import
      - name: Store run artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: artifacts-import-rke2-${{ matrix.display_name }}
          path: _out/gather
