name: Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install mdBook
      run: cargo install mdbook mdbook-fs-summary mdbook-toc

    - name: Build mdbook
      run: |
        cd docs
        mdbook build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs/book

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: gh-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

